"""Add wants_reminder field to User model

Revision ID: 9eb24ef31497
Revises: d75552f6dc42
Create Date: 2024-12-06 08:09:31.984647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb24ef31497'
down_revision = 'd75552f6dc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wants_reminder', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wants_reminder')

    # ### end Alembic commands ###
